### ISSUE TITLE
Cannot use syslog on FreeBSD without /dev/log

### ISSUE THREAD

**Issue by aiwilliams** [hashicorp/go-syslog#3]
Note the [syslogd man page](https://www.freebsd.org/cgi/man.cgi?query=syslogd&sektion=8):

> The log socket was moved from /dev to ease the use    of a read-only root file system. This may confuse some old binaries so that a symbolic link might be used for a transitional period.

We've created a symlink to allow consul to run, but I think there is a need to fix this library. [builtin.go](https://github.com/hashicorp/go-syslog/blob/ac3963b72ac367e48b1e68a831e62b93fb69091c/builtin.go#L202) copies code which has been [fixed upstream](https://github.com/golang/go/commit/5a1906dc47638840b6db96edb11ffe1fb011caad).

**Comment by sean-** [comment]
Thank you for pointing this out!

**Comment by aiwilliams** [comment]
Thank you for the fix @sean- !

**Comment by timp87** [comment]
This also makes it possible to use vault in simple jail
